# fly.toml app configuration file generated for universetime on 2024-06-06T20:26:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'universetime'
primary_region = 'nrt'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  SQLITE_PATH = '/data/db.sqlite3'

[mounts]
  source = "data"
  destination = "/data"